services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "81:81"

  shiny-server:
    container_name: shiny-server
    image: rocker/shiny:4
    working_dir: /usr/src/shiny-server
    restart: always
    ports:
      - "3838:3838"